model = "parts/rcs_block/rcs_block.glb"

name = "rcs_block_name"
country = "core:united_states"
manufacturer = "rocket_factory"
description = "rcs_block_name"

categories = ["control"]

[p_root]
	mass = 600.0

	[[p_root.attachment]]
	radial = true
	stack = true
	marker = "m_attach_top"
	size = 1.0
	name = "top_attachment"

	[[p_root.attachment]]
	radial = true
	stack = true
	marker = "m_attach_bottom"
	size = 1.0
	name = "bottom_attachment"

# Every rcs block is an engine, those engines are optionally controlled through the RCS controller

[[machine]]
	__id = "rcs_controller"
	____script = "core:machines/rcs_controller.lua"
	engines =  [
		"rcs_1px", "rcs_2px", "rcs_3px",
		"rcs_0py", "rcs_1py", "rcs_2py",
		"rcs_0pz", "rcs_1pz", "rcs_2pz", "rcs_3pz",
		"rcs_0nx", "rcs_2nx", "rcs_3nx",
		"rcs_0ny", "rcs_1ny", "rcs_3ny",
		"rcs_0nz", "rcs_1nz", "rcs_2nz", "rcs_3nz"]


# Block 0
[[machine]]
	__id = "rcs_0nx"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_0nx"
	__editor_marker = "m_0nx"

[[machine]]
	__id = "rcs_0ny"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_0ny"
	__editor_marker = "m_0ny"

[[machine]]
	__id = "rcs_0nz"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_0nz"
	__editor_marker = "m_0nz"

[[machine]]
	__id = "rcs_0py"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_0py"
	__editor_marker = "m_0py"

[[machine]]
	__id = "rcs_0pz"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_0pz"
	__editor_marker = "m_0pz"


# Block 1

[[machine]]
	__id = "rcs_1ny"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_1ny"
	__editor_marker = "m_1ny"

[[machine]]
	__id = "rcs_1nz"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_1nz"
	__editor_marker = "m_1nz"

[[machine]]
	__id = "rcs_1px"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_1px"
	__editor_marker = "m_1px"

[[machine]]
	__id = "rcs_1py"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_1py"
	__editor_marker = "m_1py"

[[machine]]
	__id = "rcs_1pz"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_1pz"
	__editor_marker = "m_1pz"

# Block 2


[[machine]]
	__id = "rcs_2nx"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_2nx"
	__editor_marker = "m_2nx"

[[machine]]
	__id = "rcs_2nz"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_2nz"
	__editor_marker = "m_2nz"

[[machine]]
	__id = "rcs_2px"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_2px"
	__editor_marker = "m_2px"

[[machine]]
	__id = "rcs_2py"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_2py"
	__editor_marker = "m_2py"

[[machine]]
	__id = "rcs_2pz"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_2pz"
	__editor_marker = "m_2pz"

# Block 3


[[machine]]
	__id = "rcs_3nx"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_3nx"
	__editor_marker = "m_3nx"

[[machine]]
	__id = "rcs_3ny"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_3ny"
	__editor_marker = "m_3ny"

[[machine]]
	__id = "rcs_3nz"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_3nz"
	__editor_marker = "m_3nz"

[[machine]]
	__id = "rcs_3px"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_3px"
	__editor_marker = "m_3px"

[[machine]]
	__id = "rcs_3pz"
	__script = "core:machines/engine.lua"
	thrust = 100.0
	__editor_hidden = true
	nozzle = "m_3pz"
	__editor_marker = "m_3pz"

