radius = 6360_000.000000000000 # meters
mass = 5.9722e24

[far_color]
	x = 0.2
	y = 0.4
	z = 1.5

[atmo]
	exponent = 1.5
	sunset_exponent = 2.5
	radius = 6500_000.000000000000 # meters, 0 for no atmosphere
	#radius = 0.0
	mie = 2e-6
	[atmo.rayleigh]
		x = 5.5e-6
		y = 13.0e-6
		z = 22.4e-6

[surface]

	script_path = "planets/earth/surface.lua"
	has_water = true
	max_height = 1000_000.0

	[surface.noise]
		seed = 0
		interp = 2

	[surface.lod]
		max_depth = 9
		coef_a = 3.0				
		coef_b = 1.2
		coef_c = 0.2
		depth_for_unload = 3

# Buildings to place as the world is created
[[building]]
	path = "buildings/launchpad.toml"
