radius = 1737_100.0 # meters
mass = 7.342e22

[far_color]
	x = 0.4
	y = 0.4
	z = 0.4

[atmo]
	exponent = 1.5
	sunset_exponent = 2.5
	radius = 0.0
	mie = 2e-6
	[atmo.rayleigh]
	x = 5.5e-6
	y = 13.0e-6
	z = 22.4e-6
[surface]

script_path = "planets/moon/surface.lua"
	has_water = true				# Does the planet have water
	max_height = 1000_000.0

	[surface.noise]
		seed = 0
		interp = 2		# 	0 = Linear < 1 = Hermite < 2 = Quintic

	[surface.lod]
		max_depth = 9
		coef_a = 3.0
		coef_b = 1.2
		coef_c = 0.2
		depth_for_unload = 3
